
import type { AgentDocument } from './types';

export const seedAgentsData: AgentDocument[] = [
  {
    name: 'Flaviane - FS',
    tomticketName: 'Atendente SAC - FS',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
  {
    name: 'Lays - LA',
    tomticketName: 'Atendente SAC - LA',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
  {
    name: 'Valquiria - VC',
    tomticketName: 'Atendente SAC - VC',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
  {
    name: 'Beatriz - BL',
    tomticketName: 'Atendente SAC - BL',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
  {
    name: 'Camila - CM',
    tomticketName: 'Atendente SAC - CM',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
  {
    name: 'Giovanna - GS',
    tomticketName: 'Atendente SAC - GS',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
    {
    name: 'Juliana - JB',
    tomticketName: 'Atendente SAC - JB',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
  {
    name: 'Laura - LC',
    tomticketName: 'Atendente SAC - LC',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
  {
    name: 'Larissa - LF',
    tomticketName: 'Atendente SAC - LF',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
  {
    name: 'Sophia - SP',
    tomticketName: 'Atendente SAC - SP',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
  {
    name: 'Lucas - LE',
    tomticketName: 'Atendente Central de Serviços - LE',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
];
