
import type { AgentDocument } from './types';

export const seedAgentsData: AgentDocument[] = [
  {
    name: 'Ana',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
  {
    name: 'Beatriz',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
  {
    name: 'Carlos',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
  {
    name: 'Daniel',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
  {
    name: 'Eduarda',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
  {
    name: 'Fernanda',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
  {
    name: 'Gustavo',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
  {
    name: 'Heitor',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
  {
    name: 'Isabela',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
  {
    name: 'João',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
];
