
import type { AgentDocument } from './types';

export const seedAgentsData: AgentDocument[] = [
  {
    name: 'Camila',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
  {
    name: 'Laura',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
  {
    name: 'Juliana',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
  {
    name: 'Flaviane',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
  {
    name: 'Beatriz',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
  {
    name: 'Sophia',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
  {
    name: 'Valquiria',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
  {
    name: 'Larissa',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
  {
    name: 'Lays',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
  {
    name: 'Giovanna',
    lastInteractionTime: new Date().toISOString(),
    activeClients: 0,
    isAvailable: true,
    totalClientsHandled: 0,
    avgTimePerClient: 0,
    isOnPause: false,
  },
];
